FROM quay.io/bgruening/galaxy-exome-seq:miracum_20.09

ADD custom-tools /galaxy-central/tools/custom-tools
ADD tool_conf.xml /galaxy-central/config/tool_conf.xml
ADD galaxy.yml /galaxy-central/config/galaxy.yml
